/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class c_jni_HelloJni */

#ifndef _Included_c_jni_HelloJni
#define _Included_c_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     c_jni_HelloJni
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_c_1jni_HelloJni_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
